update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Internal Build to Playstore internal track"
  lane :internal do
    sh "cd ../../ && flutter build appbundle"

    upload_to_play_store(
        track: "internal",
        aab: "../build/app/outputs/bundle/release/app-release.aab",
        skip_upload_images: true,
        skip_upload_screenshots: true)
        #release_status:"draft" use this for upload_to_play_store if app is only for internal use and has not been published yet
  end

  desc "Submit a new Beta Build to Playstore Beta track"
  lane :beta do
    sh "cd ../../ && flutter build appbundle"

    upload_to_play_store(
        track: "beta",
        aab: "../build/app/outputs/bundle/release/app-release.aab",
        skip_upload_images: true,
        skip_upload_screenshots: true)
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
